language: nix

script: travis_wait 240 bash -c "nix build --no-link -f ./vm.nix -o \"$(mktemp -u)/result\" --keep-going --show-trace | cachix push nothingelsematters"

before_cache:
  - mkdir -p $HOME/nix.store
  - travis_wait 30 bash -c "nix copy --no-check-sigs --to file://$HOME/nix.store $(nix build --no-link -f ./vm.nix -o \"$(mktemp -u)/result\" --keep-going --show-trace | tail -n 1)"

before_script:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf
  - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf
  - sudo pkill nix-daemon || echo "Nix daemon isn't running"
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $CACHIX_TOKEN
  - cachix use nothingelsematters

cache:
  directories:
    - $HOME/nix.store
