name: Cachix updates
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: nothingelsematters
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: cachix use nothingelsematters
      - run: nix build --no-link -I nixpkgs="$(nix eval --raw "(import nix/sources.nix).nixpkgs.outPath")" -f ./vm.nix --keep-going --show-trace
