name: Automated niv-managed dependency updates
on:
  schedule:
    - cron: '0 0 * * 4'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch_prefix: 'update/'
          message_prefix: |
            dependencies updates.
